# Generated by Django 4.0 on 2021-12-30 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_student_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='account',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.account'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='account',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.account'),
        ),
    ]
