# Generated by Django 4.0 on 2021-12-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_student_account_teacher_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classnumber',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='identity',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='identity',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='salary',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
